# NeON Build File (http://github.com/c4s4/neon)

default: run
extends:
- c4s4/build/golang.yml

properties:
  NAME:    'food'
  VERSION: '1.0.0'
  LIBRARIES:
  - 'github.com/gin-gonic/gin'
  - 'github.com/go-sql-driver/mysql'
  - 'gopkg.in/yaml.v2'

environment:
  DBHOST: 'localhost'
  DBPORT: '5432'
  DBUSER: 'postgres'
  DBPASS: ''
  DBNAME: 'pur_beurre'

targets:

  client:
    doc: Run benchmark client
    steps:
    - time:
      - $: ['go', 'run', 'client.go', 'http://localhost:8080/food/']
